// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7PI20a6P1QBvmOYbM-QZH7U1TAbYmvUo',
    appId: '1:762091419862:web:4c3a9e6b86951dceb4f177',
    messagingSenderId: '762091419862',
    projectId: 'christmas-postcard-de486',
    authDomain: 'christmas-postcard-de486.firebaseapp.com',
    storageBucket: 'christmas-postcard-de486.appspot.com',
    measurementId: 'G-WHWC64DPXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTHV-7xOgMZcXrAXGwkjq6MJ7na7R6Hc',
    appId: '1:762091419862:android:52ed3061742bbf81b4f177',
    messagingSenderId: '762091419862',
    projectId: 'christmas-postcard-de486',
    storageBucket: 'christmas-postcard-de486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpxVae5b1H3qQ9Y9gsuoMyyq3_iR9Epbw',
    appId: '1:762091419862:ios:2250a471687f31f6b4f177',
    messagingSenderId: '762091419862',
    projectId: 'christmas-postcard-de486',
    storageBucket: 'christmas-postcard-de486.appspot.com',
    iosBundleId: 'com.example.christmasPostcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpxVae5b1H3qQ9Y9gsuoMyyq3_iR9Epbw',
    appId: '1:762091419862:ios:2878f0f854e69186b4f177',
    messagingSenderId: '762091419862',
    projectId: 'christmas-postcard-de486',
    storageBucket: 'christmas-postcard-de486.appspot.com',
    iosBundleId: 'com.example.christmasPostcard.RunnerTests',
  );
}
